version: '3.7'
services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - '.:/app/frontend'
      - '/app/frontend/node_modules'
      