from pyspark.sql.types import *

# Column mappings
## KPIM
default_kpim_schema = [
	'_c0',
	'order_number',
	'order_line_number',
	'order_date',
	'order_time',
	'customer_key',
	'channel_name',
	'store_key',
	'product_key',
	'unit_price',
	'order_quantity',
	'total_sale',
	'first_name',
	'last_name',
	'loyal_group',
	'birthday',
	'gender',
	'marital_status',
	'education',
	'occupation',
	'yearly_income',
	'total_children',
	'is_active',
	'product_name',
	'product_category',
	'product_subcategory',
	'uom',
	'price',
	'cost',
	'country ',
	'brand',
	'suplier_name',
	'link',
	'product_category_image',
	'store',
	'manager',
	'manager_image',
	'city',
	'district',
	'ward',
	'address',
	'latitude',
	'longitude'
 ]

## Shopee
default_shopee_column_rename_mapping = {
    'Mã đơn hàng': 'order_number',
    'Ngày đặt hàng': 'order_date',
    'Trạng Thái Đơn Hàng': 'order_status',
	'Mã kiện hàng': 'package_code',
    'Mã vận đơn': 'tracking_code',
    'Đơn Vị Vận Chuyển': 'shipping_company',
    'Phương thức giao hàng': 'delivery_method',
    'Loại đơn hàng': 'order_type',
    'Ngày giao hàng dự kiến': 'expected_delivery_date',
    'Ngày gửi hàng': 'ship_date',
    'SKU sản phẩm': 'product_key',
    'Tên sản phẩm': 'product_name',
    'Cân nặng sản phẩm': 'weight',
    'SKU phân loại hàng': 'category_sku',
    'Tên phân loại hàng': 'product_category',
    'Giá gốc': 'price',
    'Người bán trợ giá': 'seller_discount',
    'Được Shopee trợ giá': 'shopee_discount',
    'Giá ưu đãi': 'unit_discount',
    'Số lượng': 'order_quantity',
    'Returned quantity': 'returned_quantity',  # This needs translation
    'Tổng giá bán (sản phẩm)': 'total_product_price',
    'Tổng giá trị đơn hàng (VND)': 'sales_amount',
    'Mã giảm giá của Shop': 'shop_discount_code',
    'Mã giảm giá của Shopee': 'shopee_discount_code',
    'Phí vận chuyển (dự kiến)': 'estimated_shipping_fee',
    'Phí vận chuyển mà người mua trả': 'shipping_fee_paid_by_buyer',
    'Phí vận chuyển tài trợ bởi Shopee (dự kiến)': 'shopee_sponsored_shipping_fee',
    'Phí trả hàng': 'return_fee',
    'Thời gian đơn hàng được thanh toán': 'payment_date',
    'Phương thức thanh toán': 'payment_method',
	'Người Mua': 'customer_name',
    'Tỉnh/Thành phố': 'city',
    'TP / Quận / Huyện': 'district',
    'Quận': 'ward',
    'Địa chỉ nhận hàng': 'delivery_address',
    'Quốc gia': 'country',
}

shopee_raw_schema_columns = [
    "Mã đơn hàng", "Mã Kiện Hàng", "Ngày đặt hàng", "Trạng Thái Đơn Hàng", "Lý do hủy",
    "Nhận xét từ Người mua", "Mã vận đơn", "Đơn Vị Vận Chuyển", "Phương thức giao hàng", "Loại đơn hàng",
    "Ngày giao hàng dự kiến", "Ngày gửi hàng", "Thời gian giao hàng", "Trạng thái Trả hàng/Hoàn tiền",
    "SKU sản phẩm", "Tên sản phẩm", "Cân nặng sản phẩm", "Tổng cân nặng", "SKU phân loại hàng",
    "Tên phân loại hàng", "Giá gốc", "Người bán trợ giá", "Được Shopee trợ giá",
    "Tổng số tiền được người bán trợ giá", "Giá ưu đãi", "Số lượng", "Returned quantity",
    "Tổng giá bán (sản phẩm)", "Tổng giá trị đơn hàng (VND)", "Mã giảm giá của Shop", "Hoàn Xu",
    "Mã giảm giá của Shopee", "Chỉ tiêu Combo Khuyến Mãi", "Giảm giá từ combo Shopee", "Giảm giá từ Combo của Shop",
    "Shopee Xu được hoàn", "Số tiền được giảm khi thanh toán bằng thẻ Ghi nợ",
    "Phí vận chuyển (dự kiến)", "Phí vận chuyển mà người mua trả",
    "Phí vận chuyển tài trợ bởi Shopee (dự kiến)", "Phí trả hàng", "Tổng số tiền người mua thanh toán",
    "Thời gian hoàn thành đơn hàng", "Thời gian đơn hàng được thanh toán", "Phương thức thanh toán",
    "Phí cố định", "Phí Dịch Vụ", "Phí thanh toán", "Tiền ký quỹ", "Người Mua", "Tên Người nhận",
    "Số điện thoại", "Tỉnh/Thành phố", "TP / Quận / Huyện", "Quận", "Địa chỉ nhận hàng",
    "Quốc gia", "Ghi chú"
]

shopee_bronze_schema = StructType(
[
	StructField("order_number", StringType(), True),
	StructField("order_date", DateType(), True),
	StructField("order_status", StringType(), True),
	StructField("tracking_code", StringType(), True),
	StructField("shipping_company", StringType(), True),
	StructField("delivery_method", StringType(), True),
	StructField("order_type", StringType(), True),
	StructField("ship_date", DateType(), True),
	StructField("product_key", StringType(), True),
	StructField("product_name", StringType(), True),
	StructField("weight", DoubleType(), True),
	StructField("product_category", StringType(), True),
	StructField("order_quantity", IntegerType(), True),
	StructField("price", FloatType(), True),
	StructField("seller_discount", FloatType(), True),
	StructField("shopee_discount", FloatType(), True),
	StructField("unit_discount", FloatType(), True),
	StructField("returned_quantity", IntegerType(), True),
	StructField("sales_amount", DoubleType(), True),
	StructField("promotion", StringType(), True),
	StructField("estimated_shipping_fee", FloatType(), True),
	StructField("shipping_fee_paid_by_buyer", FloatType(), True),
	StructField("shopee_sponsored_shipping_fee", FloatType(), True),
	StructField("return_fee", FloatType(), True),
	StructField("payment_date", DateType(), True),
	StructField("payment_method", StringType(), True),
	StructField("customer_name", StringType(), True),
	StructField("delivery_address", StringType(), True),
	StructField("city", StringType(), True),
	StructField("district", StringType(), True),
	StructField("ward", StringType(), True)
]
)
