version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres_user
    deploy:
      resources:
        limits:
          cpus: '0.5'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data/
    restart: always
    networks:
      - backendnetwork

  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
    ports:
      - '8000:8000'
    restart: always
    networks:
      - backendnetwork
    volumes:
      - '.:/app/backend'
      - '//var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - db
    
  # mysql:
  #   image: mysql:latest
  #   container_name: mysql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: test
  #     MYSQL_PASSWORD: root
  #   restart: always
  #   networks:
  #     - backendnetwork
  #   volumes:
  #     - ../user_db/mysql:/var/lib/mysql

networks:
  backendnetwork:
    driver: bridge

  
      