version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data/
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - WDS_SOCKET_HOST=127.0.0.1 
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true 
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   depends_on:
  #     - backend

  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - '.:/app/backend'
    depends_on:
      - db
